### ISSUE TITLE
Removing SD Card results in Error

### ISSUE THREAD

**Issue by GabrielRRussell** [devkitPro/3ds-hbmenu#1]
The original HBL would work if you removed the SD card, so you could remount it with more software. This feature does not work in this HBL, and instead, forces you to reboot. Please consider putting in an implementation of this in a future version.

**Comment by fincs** [comment]
This is intentional. As stated in the Readme, "You should not hotswap the SD card while hbmenu is running since it compromises the 3DS OS's stability amongst other things. It is recommended that you instead use a file transfer homebrew application such as ftpd to transfer files without rebooting."
This is now more relevant since the real HOME menu is now running in the background.

**Comment by DumbJoe** [comment]
what if the card ejects itself randomly? ...may as well allow hotswapping since you can do this with the game carts.....
