### ISSUE TITLE
Problem with some Homebrew Apps,Not showing up in the Homebrew Launcher Menu

### ISSUE THREAD

**Issue by heirzaa** [devkitPro/3ds-hbmenu#17]
Hi!
Recently, I decided to upgrade luma to version 8.0 and install this new version of the Homebrew Menu
and...
Its amazing
The simply fact of you can access to the Home menu directly like any other 3ds game its really great!
But,some apps didn't show in the homebrew menu,like hans,for example
I have all the right files in my 3ds folder
Please help me,I need hans since the region emulator of Luma doesn't work for me,for play out of region dlc 
I'm not the only one with this issue,i found similar cases in diferent forums
Sorry for my poor english,my native language is spanish...
And i'm really new in this kind of themes
I dont know if i'm doing right to contact you
Or i need to contact hans developer
Greetings from Chile!

**Comment by fincs** [comment]
HANS requires certain things that can only be provided by hax 2.x, and hax 2.x cannot run under Luma3DS due to changes in the memory layout that had to be made to accomodate Rosalina. For this reason, HANS is hidden/disabled when running under Rosalina (or actually, anything that is not hax 2.x). Please note that since you have Luma3DS, you can use its built-in ExeFS/RomFS (LayeredFS) game patching feature - HANS is actually obsolete. It should be easy to get existing HANS-based romhacks working natively with Luma3DS.

>HANS necesita algunas cosas que solo pueden ser proporcionadas por hax 2.x, y debido a cambios en la disposición de los datos en la memoria RAM de la 3DS (necesarios para acomodar el nuevo módulo Rosalina), ya no es posible ejecutar hax 2.x bajo Luma3DS. Debido a este motivo, decidí ocultar el icono de HANS cuando se está usando Rosalina (en realidad, cuando se está utilizando cualquier cosa que no sea hax 2.x para correr hbmenu). Ten en cuenta que ya que ya tienes Luma3DS instalado, puedes usar su función incorporada de parcheo de ExeFS/RomFS (LayeredFS) - HANS está obsoleto de hecho. Debería de ser sencillo convertir hackroms de HANS para correr nativamente con Luma3DS.

**Comment by NightScript370** [comment]
What about ReiNAND B9S users?
