### ISSUE TITLE
Error upon attempting to launch an app that needs to target titles

### ISSUE THREAD

**Issue by 0ICED0** [devkitPro/3ds-hbmenu#19]
This homebrew exploit does not have support for launching applications under target titles. Please use another exploit. This is the message I get from attempting loading braindump.

**Comment by Committee** [comment]
Error means exactly what it says, applications that need to select/target specific titles are not supported anymore in Luma Versions 8.0 and above.

**Comment by fincs** [comment]
This is intentional. It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

Also, HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature. You can also use GodMode9 instead of braindump for dumping game assets.

**Comment by VinodJIsaac** [comment]
I am trying to launch the OOThax on homebrew. How else can I do it? 
and what is a target title?

**Comment by urherenow** [comment]
Please ask on the gbatemp forums. Github issues are reporting bugs, not for tech support, and this issue was CLOSED AGES AGO.

**Comment by VinodJIsaac** [comment]
Wow Thanks a lot for your HELP :D

**Comment by CeeJayBeenz** [comment]
Dude, he was just trying to help you by sending you to a place where people will ACTUALLY answer your question instead of ignoring it. Stop being ignorant, and go on GBATemp.
