### ISSUE TITLE
Hans

### ISSUE THREAD

**Issue by alpuy** [devkitPro/3ds-hbmenu#27]
Could you add hans support? Its really useful to take screenshots and launch titles from homebrew Launcher

**Comment by fincs** [comment]
This is intentional. HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature. You can also use Rosalina's menu to take screenshots. And of course you can return to home menu at any time by pressing the HOME button.

hax 2.x cannot run because Rosalina reorganizes system memory layout and is therefore inherently incompatible.
