### ISSUE TITLE
Some Homebrews are Broken With The Rosalina Entrypoint

### ISSUE THREAD

**Issue by qimiko** [devkitPro/3ds-hbmenu#3]
My current list:

ctr-httpwn
DSP Dump

DSP Dump shows that a hax 2.0 payload is needed

Entrypoint: Rosalina, Luma v8.0
3DS Version: 11.3.0-36U (Old 3DS)

**Comment by saphtea** [comment]
I can confirm for DSP Dump.

There's issues also occurring with LuaRed (an flexible gameboy emulator mainly centered around Pokemon Red) that actually causes it to crash as a whole.

**Luared Crash**
Preview: ![image](https://cloud.githubusercontent.com/assets/272940/26775338/5ea720d2-4989-11e7-8364-c118d4bccc43.png)

Dump: [crash_dump_00000002.zip](https://github.com/fincs/new-hbmenu/files/1051407/crash_dump_00000002.zip)

Not sure if this has to do with HBL or with the entrypoint being Rosalina though. Please do tell me if this should be reported under Luma3DS' issue tracker instead!

Device Details:
New 3DS XL
11.4.0-37U
Boot9Strap 1.2
Luma 3DS 8.0

**Comment by fincs** [comment]
- DSP Dump: This requires a mechanism that only hax 2.x is able to provide: when it takes over the home menu process, it extracts home menu's DSP firmware and passes it to launched homebrew as a shared memory through the stolen handle table (the latter doesn't exist anymore in Rosalina).
- ctr-httpwn: This homebrew is completely obsolete. If you have CFW, there is nothing stopping you from updating to the latest system version.
- Lua players: We will investigate. But as @Saphiresurf suggested, this should be reported on the Luma3DS repo as a Rosalina issue instead of here. hbmenu merely calls a few Rosalina commands to get 3dsx files executed.

**Comment by GabrielRRussell** [comment]
While I agree with the other two, I don't agree with your statement on ctr-httpwn being obsolete. It's pretty darn useful for people staying on lower FWs for certain homebrew. While now we don't have to wait for a new *hax payload (aside from stock ofw), NTR streaming was broken for a while, and some people had to stay behind.

But yeah factual for the rest.

**Comment by fincs** [comment]
There is no reason to stay on lower firmware reasons with all the patches and checks put by Luma3DS. Also, the latest system version patched the flaw used by ctr-httpwn so it doesn't work anymore at all.

Update on DSP Dump thing: I've been informed that [DSP1 exists](https://github.com/zoogie/DSP1).

**Comment by TuxSH** [comment]
DSP1 is also what is used by the guide. It does its job then uninstalls itself in a keypress.

**Comment by fincs** [comment]
Update: I have tried looking into the Lua Red issue, however it looks like the homebrew app has been pruned from the face of the earth by the author. Obviously nothing can be done about this now.
