### ISSUE TITLE
Homebrew requiring title selection (ex. SVDT) don't work.

### ISSUE THREAD

**Issue by sks316** [devkitPro/3ds-hbmenu#4]
Read title. These homebrew return an error.

**Comment by ghost** [comment]
I'm pretty sure that's intended, but I'd like support for that to be added at some point (if technically feasible, at least.)

**Comment by fincs** [comment]
This is intentional. It was decided that target title selection is not useful anymore since 3dsx applications have full ARM11 system permissions now, and it is possible to directly access the savefiles of any title by using the appropriate FSUSER commands. In the meantime, you can use the CIA versions of savegame managers.

**Comment by sks316** [comment]
Why is it "not useful anymore?" SVDT (and other applications like it) have no CIA version. -_- I'd like for at least an effort to add support for it.

**Comment by ghost** [comment]
"Not useful anymore" because (at least the vast majority of) apps that used target title selection have their features available through other means (be it .cia homebrew in the case of save managers, or NTR/LayeredFS for HANS, and region free being a thing by default in luma.)

The target title selection worked by booting into the selected app and hijacking the process to allow access to things like save files which you couldn't otherwise access. This is obsolete since, as it was just said, 3dsx homebrew have full ARM11 access under Rosalina HBL-2.0.0 and can just directly access savedata instead.

I prefer the way svdt works over JKSM and rather install as few .cia homebrew as possible, but the logic is sound. Anybody can fork svdt to add an integrated game selection menu,  which would work with HBL 2.0.0, but this isn't something I have the required knowledge to do right now and I doubt the interest is really here for anyone else to really bother spending the time updating most old homebrew.

You can always look into it yourself (myself and perhaps several others would be appreciative if someone did), though you're on your own when it comes to finding the resources you need for learning.

**Comment by Phalk** [comment]
The logic is pretty sound yeah, but this should have been kept at least for compatibility reasons IMO.
Also, Homebrew developers would be needing to keep 2 separate releases of their 3dsx apps to cover for that, because there are still people who are locked into userland homebrew environments by choice.

**Comment by ghost** [comment]
The userbase in this scenario is small enough that it may not really be worth the dev time, tbh.

It's reasonably safe to assume that a user running Luma 8.0 hasn't had HANS on their SD card in ages, so we can rule that one out.
As far as save managers go, the vast majority of CFW users have opted for SaveDataFiler or JKSM a long time ago; those of us who preferred running 3dsx save managers were a small minority.

The only other homebrew with target title selection I can think of right now is PHBank, and this has a .cia pre-release; disregarding the cia release, that app is likely popular enough to have demand for it, and HBL 2.0.0 support would really improve the app anyway (if enough people cared about running the 3dsx over the .cia, at least. This applies to svdt, too.)

My main issue with it is that unless you stayed behind in b9s 1.0/Luma 7.1, you don't even have an option. At the end of the day, though, both AW and fincs have every right to stop supporting legacy homebrew that is only used by a small minority of their userbase. There are always other CFWs available, so if one really wants to run those older homebrew, dual-booting a second CFW whenever they want to use HBL is always an option.

(That being said, this is open-source and on Github, so if someone out there wants target title selection support badly enough, they can work on it themselves and submit a pull request :p doesn't have to be fincs)

**Comment by sks316** [comment]
That being said, there's still a problem with save managers. Not every save manager has the anti-cheat protection that SVDT has, and as far as I know SVDT has no CIA. I don't use a second CFW because simplicity. Surely it can't be hard.

**Comment by ghost** [comment]
I'm pretty sure JKSM does secure values automatically, and so do the newer versions of SDF. The only save manager I'm aware of that doesn't handle it is the original save_manager and no one should have been using that over svdt anyway.

**Comment by sks316** [comment]
Let's just do it for the people who like 3DSX homebrew and don't prefer cluttering their HOME Menu with applications.
