### ISSUE TITLE
3DS won't boot without SD card

### ISSUE THREAD

**Issue by distay0xGit** [devkitPro/3ds-hbmenu#42]
Whenever I power my 3DS on, and the SD card is removed, it doesn't boot up. Does this have something to do with the Homebrew Launcher, or the Luma3DS firm?

Also, what programs can open .lz files? I'm trying to enter the images.lz, but I'm not having any luck.

**Comment by fincs** [comment]
Yeah, this has nothing to do with Homebrew Menu or Luma3DS.

B9S tries to load boot.firm from SD card, and then if that fails, from NAND. If that also fails, it shuts the console off. If you want to be able to boot your 3DS without an SD card, put Luma's boot.firm in the root of CTRNAND with GodMode9. Please note however that nothing homebrew related will work since it assumes a SD card is present and .3dsx can be loaded from them.

**Comment by distay0xGit** [comment]
Still, is there any way to decompress and recompress the "images.lz" file?
