### ISSUE TITLE
No more HANS or region free launcher?

### ISSUE THREAD

**Issue by gingerbeardman** [devkitPro/3ds-hbmenu#7]
I have HANS on my SD card but it is not showing up in the launcher.

I use it to run an out of region game that LUMA will not launch even with locale settings.

**Comment by fincs** [comment]
HANS is obsoleted by Luma3DS's built-in ExeFS/RomFS (LayeredFS) game patching feature.
Region free launcher is obsoleted by Luma3DS's region free patches.

**Comment by gingerbeardman** [comment]
Thanks! Just the info I needed. I will look into both.

**Comment by YukariTea** [comment]
Even if that is true, why purposely hide HANS just because it is obsolete? Additionally, HANS also has the niche of taking screenshots at a not too slow speed, at the precise moment we want, which Luma3DS doesn't offer. (And the Luma3DS option to take screenshots requires opening a menu with the L button, a commonly broken o3ds shoulder button)

**Comment by fincs** [comment]
1) HANS is only hidden when using Rosalina because it doesn't work, there is no way to make it work and there is no point in making it work when ExeFS/RomFS patching is a built-in Luma3DS feature.
2) Screenshot feature has nothing to do with HANS; and over time Rosalina's screenshot feature will improve.
3) You can change the Rosalina menu keycombo (and it will be possible to save it to a configuration file in the future).
