### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by cooolgamer** [devkitPro/3ds-hbmenu#72]
hello, I want to compile the homebrew launcher but it give me an error:
![image](https://user-images.githubusercontent.com/64099608/105607454-21039c00-5d9f-11eb-943c-5449bb9bb469.png)
it's possible to help me?

thanks.

**Comment by fincs** [comment]
? https://github.com/fincs/new-hbmenu#building

Also, why are you trying to build this?

**Comment by urherenow** [comment]
Wow this issue is old. It can be closed as there are no building issues with one slight tweak of the readme (pull request submitted https://github.com/devkitPro/3ds-hbmenu/pull/87 )

pacman -S 3ds-zlib 3ds-tinyxml2 3ds-libconfig

As for why I build things, I like to be on the bleeding edge, but spend half of every year out to sea. I can 't connect my personal pc/laptop to the internet during this time, but I can see commit texts from my work machine.
